// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: internal/transfer/models/transfer_request.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Filename        string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Extension       string                 `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	FileSize        uint64                 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	Mime            string                 `protobuf:"bytes,7,opt,name=mime,proto3" json:"mime,omitempty"`
	SenderIp        string                 `protobuf:"bytes,8,opt,name=sender_ip,json=senderIp,proto3" json:"sender_ip,omitempty"`
	SenderName      string                 `protobuf:"bytes,9,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	ClientName      string                 `protobuf:"bytes,10,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion   string                 `protobuf:"bytes,11,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_internal_transfer_models_transfer_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transfer_models_transfer_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_internal_transfer_models_transfer_request_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *TransferRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TransferRequest) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *TransferRequest) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *TransferRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransferRequest) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *TransferRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *TransferRequest) GetSenderIp() string {
	if x != nil {
		return x.SenderIp
	}
	return ""
}

func (x *TransferRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *TransferRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *TransferRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

var File_internal_transfer_models_transfer_request_proto protoreflect.FileDescriptor

const file_internal_transfer_models_transfer_request_proto_rawDesc = "" +
	"\n" +
	"/internal/transfer/models/transfer_request.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x03\n" +
	"\x0fTransferRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1c\n" +
	"\textension\x18\x03 \x01(\tR\textension\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x04R\bfileSize\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x12\n" +
	"\x04mime\x18\a \x01(\tR\x04mime\x12\x1b\n" +
	"\tsender_ip\x18\b \x01(\tR\bsenderIp\x12\x1f\n" +
	"\vsender_name\x18\t \x01(\tR\n" +
	"senderName\x12\x1f\n" +
	"\vclient_name\x18\n" +
	" \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\v \x01(\tR\rclientVersionB\"Z airlink/internal/transfer/modelsb\x06proto3"

var (
	file_internal_transfer_models_transfer_request_proto_rawDescOnce sync.Once
	file_internal_transfer_models_transfer_request_proto_rawDescData []byte
)

func file_internal_transfer_models_transfer_request_proto_rawDescGZIP() []byte {
	file_internal_transfer_models_transfer_request_proto_rawDescOnce.Do(func() {
		file_internal_transfer_models_transfer_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transfer_models_transfer_request_proto_rawDesc), len(file_internal_transfer_models_transfer_request_proto_rawDesc)))
	})
	return file_internal_transfer_models_transfer_request_proto_rawDescData
}

var file_internal_transfer_models_transfer_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_transfer_models_transfer_request_proto_goTypes = []any{
	(*TransferRequest)(nil),       // 0: TransferRequest
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_internal_transfer_models_transfer_request_proto_depIdxs = []int32{
	1, // 0: TransferRequest.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: TransferRequest.modified_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_transfer_models_transfer_request_proto_init() }
func file_internal_transfer_models_transfer_request_proto_init() {
	if File_internal_transfer_models_transfer_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transfer_models_transfer_request_proto_rawDesc), len(file_internal_transfer_models_transfer_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_transfer_models_transfer_request_proto_goTypes,
		DependencyIndexes: file_internal_transfer_models_transfer_request_proto_depIdxs,
		MessageInfos:      file_internal_transfer_models_transfer_request_proto_msgTypes,
	}.Build()
	File_internal_transfer_models_transfer_request_proto = out.File
	file_internal_transfer_models_transfer_request_proto_goTypes = nil
	file_internal_transfer_models_transfer_request_proto_depIdxs = nil
}
